# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kevin/Documents/Programming/CPE476/Hear-No-Evil-See-No-Evil

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kevin/Documents/Programming/CPE476/Hear-No-Evil-See-No-Evil

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kevin/Documents/Programming/CPE476/Hear-No-Evil-See-No-Evil/CMakeFiles /Users/kevin/Documents/Programming/CPE476/Hear-No-Evil-See-No-Evil/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kevin/Documents/Programming/CPE476/Hear-No-Evil-See-No-Evil/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project

# Build rule for target.
Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project
.PHONY : Project

# fast build rule for target.
Project/fast:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/build
.PHONY : Project/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f dependencies/glfw/src/CMakeFiles/glfw.dir/build.make dependencies/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

dependencies/glad/src/glad.o: dependencies/glad/src/glad.c.o
.PHONY : dependencies/glad/src/glad.o

# target to build an object file
dependencies/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/dependencies/glad/src/glad.c.o
.PHONY : dependencies/glad/src/glad.c.o

dependencies/glad/src/glad.i: dependencies/glad/src/glad.c.i
.PHONY : dependencies/glad/src/glad.i

# target to preprocess a source file
dependencies/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/dependencies/glad/src/glad.c.i
.PHONY : dependencies/glad/src/glad.c.i

dependencies/glad/src/glad.s: dependencies/glad/src/glad.c.s
.PHONY : dependencies/glad/src/glad.s

# target to generate assembly for a file
dependencies/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/dependencies/glad/src/glad.c.s
.PHONY : dependencies/glad/src/glad.c.s

source/Camera/Camera.o: source/Camera/Camera.cpp.o
.PHONY : source/Camera/Camera.o

# target to build an object file
source/Camera/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Camera/Camera.cpp.o
.PHONY : source/Camera/Camera.cpp.o

source/Camera/Camera.i: source/Camera/Camera.cpp.i
.PHONY : source/Camera/Camera.i

# target to preprocess a source file
source/Camera/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Camera/Camera.cpp.i
.PHONY : source/Camera/Camera.cpp.i

source/Camera/Camera.s: source/Camera/Camera.cpp.s
.PHONY : source/Camera/Camera.s

# target to generate assembly for a file
source/Camera/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Camera/Camera.cpp.s
.PHONY : source/Camera/Camera.cpp.s

source/GameObject/GameObject.o: source/GameObject/GameObject.cpp.o
.PHONY : source/GameObject/GameObject.o

# target to build an object file
source/GameObject/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/GameObject.cpp.o
.PHONY : source/GameObject/GameObject.cpp.o

source/GameObject/GameObject.i: source/GameObject/GameObject.cpp.i
.PHONY : source/GameObject/GameObject.i

# target to preprocess a source file
source/GameObject/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/GameObject.cpp.i
.PHONY : source/GameObject/GameObject.cpp.i

source/GameObject/GameObject.s: source/GameObject/GameObject.cpp.s
.PHONY : source/GameObject/GameObject.s

# target to generate assembly for a file
source/GameObject/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/GameObject.cpp.s
.PHONY : source/GameObject/GameObject.cpp.s

source/GameObject/Handles.o: source/GameObject/Handles.cpp.o
.PHONY : source/GameObject/Handles.o

# target to build an object file
source/GameObject/Handles.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Handles.cpp.o
.PHONY : source/GameObject/Handles.cpp.o

source/GameObject/Handles.i: source/GameObject/Handles.cpp.i
.PHONY : source/GameObject/Handles.i

# target to preprocess a source file
source/GameObject/Handles.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Handles.cpp.i
.PHONY : source/GameObject/Handles.cpp.i

source/GameObject/Handles.s: source/GameObject/Handles.cpp.s
.PHONY : source/GameObject/Handles.s

# target to generate assembly for a file
source/GameObject/Handles.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Handles.cpp.s
.PHONY : source/GameObject/Handles.cpp.s

source/GameObject/Mesh.o: source/GameObject/Mesh.cpp.o
.PHONY : source/GameObject/Mesh.o

# target to build an object file
source/GameObject/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Mesh.cpp.o
.PHONY : source/GameObject/Mesh.cpp.o

source/GameObject/Mesh.i: source/GameObject/Mesh.cpp.i
.PHONY : source/GameObject/Mesh.i

# target to preprocess a source file
source/GameObject/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Mesh.cpp.i
.PHONY : source/GameObject/Mesh.cpp.i

source/GameObject/Mesh.s: source/GameObject/Mesh.cpp.s
.PHONY : source/GameObject/Mesh.s

# target to generate assembly for a file
source/GameObject/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Mesh.cpp.s
.PHONY : source/GameObject/Mesh.cpp.s

source/GameObject/Player.o: source/GameObject/Player.cpp.o
.PHONY : source/GameObject/Player.o

# target to build an object file
source/GameObject/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Player.cpp.o
.PHONY : source/GameObject/Player.cpp.o

source/GameObject/Player.i: source/GameObject/Player.cpp.i
.PHONY : source/GameObject/Player.i

# target to preprocess a source file
source/GameObject/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Player.cpp.i
.PHONY : source/GameObject/Player.cpp.i

source/GameObject/Player.s: source/GameObject/Player.cpp.s
.PHONY : source/GameObject/Player.s

# target to generate assembly for a file
source/GameObject/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Player.cpp.s
.PHONY : source/GameObject/Player.cpp.s

source/GameObject/Shape.o: source/GameObject/Shape.cpp.o
.PHONY : source/GameObject/Shape.o

# target to build an object file
source/GameObject/Shape.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Shape.cpp.o
.PHONY : source/GameObject/Shape.cpp.o

source/GameObject/Shape.i: source/GameObject/Shape.cpp.i
.PHONY : source/GameObject/Shape.i

# target to preprocess a source file
source/GameObject/Shape.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Shape.cpp.i
.PHONY : source/GameObject/Shape.cpp.i

source/GameObject/Shape.s: source/GameObject/Shape.cpp.s
.PHONY : source/GameObject/Shape.s

# target to generate assembly for a file
source/GameObject/Shape.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Shape.cpp.s
.PHONY : source/GameObject/Shape.cpp.s

source/GameObject/Wall.o: source/GameObject/Wall.cpp.o
.PHONY : source/GameObject/Wall.o

# target to build an object file
source/GameObject/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Wall.cpp.o
.PHONY : source/GameObject/Wall.cpp.o

source/GameObject/Wall.i: source/GameObject/Wall.cpp.i
.PHONY : source/GameObject/Wall.i

# target to preprocess a source file
source/GameObject/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Wall.cpp.i
.PHONY : source/GameObject/Wall.cpp.i

source/GameObject/Wall.s: source/GameObject/Wall.cpp.s
.PHONY : source/GameObject/Wall.s

# target to generate assembly for a file
source/GameObject/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/GameObject/Wall.cpp.s
.PHONY : source/GameObject/Wall.cpp.s

source/Library/GLSL.o: source/Library/GLSL.cpp.o
.PHONY : source/Library/GLSL.o

# target to build an object file
source/Library/GLSL.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/GLSL.cpp.o
.PHONY : source/Library/GLSL.cpp.o

source/Library/GLSL.i: source/Library/GLSL.cpp.i
.PHONY : source/Library/GLSL.i

# target to preprocess a source file
source/Library/GLSL.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/GLSL.cpp.i
.PHONY : source/Library/GLSL.cpp.i

source/Library/GLSL.s: source/Library/GLSL.cpp.s
.PHONY : source/Library/GLSL.s

# target to generate assembly for a file
source/Library/GLSL.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/GLSL.cpp.s
.PHONY : source/Library/GLSL.cpp.s

source/Library/InitObjects.o: source/Library/InitObjects.cpp.o
.PHONY : source/Library/InitObjects.o

# target to build an object file
source/Library/InitObjects.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/InitObjects.cpp.o
.PHONY : source/Library/InitObjects.cpp.o

source/Library/InitObjects.i: source/Library/InitObjects.cpp.i
.PHONY : source/Library/InitObjects.i

# target to preprocess a source file
source/Library/InitObjects.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/InitObjects.cpp.i
.PHONY : source/Library/InitObjects.cpp.i

source/Library/InitObjects.s: source/Library/InitObjects.cpp.s
.PHONY : source/Library/InitObjects.s

# target to generate assembly for a file
source/Library/InitObjects.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/InitObjects.cpp.s
.PHONY : source/Library/InitObjects.cpp.s

source/Library/TimeManager.o: source/Library/TimeManager.cpp.o
.PHONY : source/Library/TimeManager.o

# target to build an object file
source/Library/TimeManager.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/TimeManager.cpp.o
.PHONY : source/Library/TimeManager.cpp.o

source/Library/TimeManager.i: source/Library/TimeManager.cpp.i
.PHONY : source/Library/TimeManager.i

# target to preprocess a source file
source/Library/TimeManager.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/TimeManager.cpp.i
.PHONY : source/Library/TimeManager.cpp.i

source/Library/TimeManager.s: source/Library/TimeManager.cpp.s
.PHONY : source/Library/TimeManager.s

# target to generate assembly for a file
source/Library/TimeManager.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/TimeManager.cpp.s
.PHONY : source/Library/TimeManager.cpp.s

source/Library/tiny_obj_loader.o: source/Library/tiny_obj_loader.cc.o
.PHONY : source/Library/tiny_obj_loader.o

# target to build an object file
source/Library/tiny_obj_loader.cc.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/tiny_obj_loader.cc.o
.PHONY : source/Library/tiny_obj_loader.cc.o

source/Library/tiny_obj_loader.i: source/Library/tiny_obj_loader.cc.i
.PHONY : source/Library/tiny_obj_loader.i

# target to preprocess a source file
source/Library/tiny_obj_loader.cc.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/tiny_obj_loader.cc.i
.PHONY : source/Library/tiny_obj_loader.cc.i

source/Library/tiny_obj_loader.s: source/Library/tiny_obj_loader.cc.s
.PHONY : source/Library/tiny_obj_loader.s

# target to generate assembly for a file
source/Library/tiny_obj_loader.cc.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/Library/tiny_obj_loader.cc.s
.PHONY : source/Library/tiny_obj_loader.cc.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Project"
	@echo "... glfw"
	@echo "... dependencies/glad/src/glad.o"
	@echo "... dependencies/glad/src/glad.i"
	@echo "... dependencies/glad/src/glad.s"
	@echo "... source/Camera/Camera.o"
	@echo "... source/Camera/Camera.i"
	@echo "... source/Camera/Camera.s"
	@echo "... source/GameObject/GameObject.o"
	@echo "... source/GameObject/GameObject.i"
	@echo "... source/GameObject/GameObject.s"
	@echo "... source/GameObject/Handles.o"
	@echo "... source/GameObject/Handles.i"
	@echo "... source/GameObject/Handles.s"
	@echo "... source/GameObject/Mesh.o"
	@echo "... source/GameObject/Mesh.i"
	@echo "... source/GameObject/Mesh.s"
	@echo "... source/GameObject/Player.o"
	@echo "... source/GameObject/Player.i"
	@echo "... source/GameObject/Player.s"
	@echo "... source/GameObject/Shape.o"
	@echo "... source/GameObject/Shape.i"
	@echo "... source/GameObject/Shape.s"
	@echo "... source/GameObject/Wall.o"
	@echo "... source/GameObject/Wall.i"
	@echo "... source/GameObject/Wall.s"
	@echo "... source/Library/GLSL.o"
	@echo "... source/Library/GLSL.i"
	@echo "... source/Library/GLSL.s"
	@echo "... source/Library/InitObjects.o"
	@echo "... source/Library/InitObjects.i"
	@echo "... source/Library/InitObjects.s"
	@echo "... source/Library/TimeManager.o"
	@echo "... source/Library/TimeManager.i"
	@echo "... source/Library/TimeManager.s"
	@echo "... source/Library/tiny_obj_loader.o"
	@echo "... source/Library/tiny_obj_loader.i"
	@echo "... source/Library/tiny_obj_loader.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

