if (FREETYPE_LIBRARIES AND FREETYPE_INCLUDE_DIRS)
# in cache already
set(FREETYPE_FOUND TRUE)
else (FREETYPE_LIBRARIES AND FREETYPE_INCLUDE_DIRS)

find_path(FREETYPE_INCLUDE_DIR
  NAMES
  ftheader.h 
  PATHS
  ${PROJECT_SOURCE_DIR}/dependencies/freetype-2.4.0/include
)

find_library(FREEPATH_LIBRARY
  NO_DEFAULT_PATH
  PATH_SUFFIXES
  lib
  NAMES
  freetext
  PATHS
  ${PROJECT_SOURCE_DIR}/dependencies/freetype-2.4.0/bin/macosx-gcc
)


if (FREETYPE_LIBRARY)
set(FREETYPE_FOUND TRUE)
endif (FREETYPE_LIBRARY)

set(FREETYPE_INCLUDE_DIRS
    ${FREETYPE_INCLUDE_DIR}
   )

if (FREETYPE_FOUND)
set(FREETYPE_LIBRARIES
    ${FREETYPE_LIBRARIES}
    ${FREETYPE_LIBRARY}
   )
endif (FREETYPE_FOUND)

if (FREETYPE_INCLUDE_DIRS AND FREETYPE_LIBRARIES)
set(FREETYPE_FOUND TRUE)
endif (FREETYPE_INCLUDE_DIRS AND FREETYPE_LIBRARIES)

if (FREETYPE_FOUND)
if (NOT FREETYPE_FIND_QUIETLY)
message(STATUS "Found freetype: ${FREETYPE_LIBRARIES}")
endif (NOT FREETYPE_FIND_QUIETLY)
else (FREETYPE_FOUND)
if (FREETYPE_FIND_REQUIRED)
message(FATAL_ERROR "Could not find FREETYPE")
endif (FREETYPE_FIND_REQUIRED)
endif (FREETYPE_FOUND)

# show the FREETYPE_INCLUDE_DIRS and FREETYPE_LIBRARIES variables only in the advanced view
mark_as_advanced(FREETYPE_INCLUDE_DIRS FREETYPE_LIBRARIES)

endif (FREETYPE_LIBRARIES AND FREETYPE_INCLUDE_DIRS)
